kind: pipeline
type: kubernetes
name: build

steps:
  - name: yarn build
    image: node:16.17-alpine
    commands:
      - apk add git
      - yarn config list
      - yarn install --network-timeout 600000
      - yarn run docs:build

  - name: docker build & push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: northes/apihut-docs
      tags: dev-${DRONE_COMMIT_SHA:0:8}

trigger:
  branch:
    - dev

---
kind: pipeline
type: kubernetes
name: build && deploy

steps:
  - name: yarn build
    image: node:16.17-alpine
    commands:
      - apk add git
      - yarn config list
      - yarn install --network-timeout 600000
      - yarn run docs:build

  - name: docker build & push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: northes/apihut-docs
      tags: ${DRONE_TAG##v}

  - name: "chart package"
    image: alpine/helm:3.10.1
    environment:
      username:
        from_secret: helm_username
      password:
        from_secret: helm_password
    commands:
      - helm repo add chartmuseum https://charts.northes.co --username=$username --password=$password
      - helm plugin install https://github.com/chartmuseum/helm-push
      - helm cm-push ./deploy/chart chartmuseum --version=${DRONE_TAG##v} --app-version=${DRONE_TAG##v}

trigger:
  event:
    - tag