kind: pipeline
type: kubernetes
name: build

steps:
  - name: yarn build
    image: node:16.17-alpine
    commands:
      - apk add git
      - yarn config list
      - yarn install --network-timeout 600000
      - yarn run docs:build

  - name: docker build tag & push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: harbor.northes.co/apihut/docs
      tags: ${DRONE_TAG##v}
      registry: harbor.northes.co
    when:
      event:
        - tag

  - name: docker build hash & push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: harbor.northes.co/apihut/docs
      tags: ${DRONE_COMMIT_SHA:0:8}
      registry: harbor.northes.co
      when:
        branch:
          - dev

trigger:
  branch:
    - main
    - dev
